name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      LOGIN_EMAIL: 'dummy'
      LOGIN_PASSWORD: 'dummy'
      BOT_TOKEN: 'dummy'
      CHAT_ID: 123

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build
        run: pip install -r requirements.txt

      - name: Test
        run: python -m unittest discover -v